# Generated by Django 5.2.17 on 2026-09-15 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("company", "0002_company_logo_storage_key_company_logo_url"),
        ("leads", "0001_initial"),
        ("projects", "0003_project_status_before_hold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "visit_date",
                    models.DateTimeField(
                        help_text="When this site visit is scheduled to occur."
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The site address to visit.",
                        max_length=500,
                    ),
                ),
                (
                    "measurements",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text measurements captured on site.",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text client requirements captured on site.",
                    ),
                ),
                (
                    "photo_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of photo URLs captured for this visit.",
                    ),
                ),
                (
                    "video_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of video URLs captured for this visit.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form internal notes about this visit.",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget discussed/estimated during this visit, if any.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "site_conditions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text notes on the physical site conditions.",
                    ),
                ),
                (
                    "follow_up_actions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text follow-up actions agreed during this visit.",
                    ),
                ),
                (
                    "report_submitted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Set only by SiteVisitService.submit_report — the one true completion signal for this visit.",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person assigned to carry out this site visit, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_site_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved automatically from lead.converted_client/project.client at creation — never independently settable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits",
                        to="clients.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this site visit belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_visits",
                        to="company.company",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="The lead this site visit was scheduled against, if any (pre-conversion prospecting).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits",
                        to="leads.lead",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The project this site visit was scheduled against, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "site visit",
                "verbose_name_plural": "site visits",
                "db_table": "site_visit",
                "ordering": ["-visit_date"],
                "indexes": [
                    models.Index(
                        fields=["company", "visit_date"],
                        name="sitevisit_company_date_idx",
                    ),
                    models.Index(
                        fields=["company", "assigned_to"],
                        name="sitevisit_company_assignee_idx",
                    ),
                ],
            },
        ),
    ]
