# Generated by Django 5.2.17 on 2026-08-27 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Project name.", max_length=255)),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Planned project start date.", null=True
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, help_text="Planned project deadline.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planning", "Planning"),
                            ("design", "Design"),
                            ("quotation", "Quotation"),
                            ("approved", "Approved"),
                            ("execution", "Execution"),
                            ("quality_check", "Quality Check"),
                            ("handover", "Handover"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Project lifecycle status.",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text priority signal. No documented value domain exists (01_Business/FRS.md §10 names the field but never defines values) — deliberately left unconstrained per Backend Lead decision (2026-08-27) rather than inventing an enum.",
                        max_length=50,
                    ),
                ),
                (
                    "follow_up_reminder_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional follow-up reminder timestamp.",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Single responsible user (Database_Schema.md's `assigned_to` column) — not the multi-user \"team\" concept implied by 04_API/Project_API.md's /team endpoints, which has no corresponding table in Migration_Plan.md and is deferred to BE-025. Future invariant (not yet enforced — no assignment service exists yet): assigned_to must belong to the same Company as this Project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this project is for. PROTECT per 03_Database/Naming_Standards.md §4 — a client with existing projects must not be hard-deleted. Soft-deleting a client never triggers this (SoftDeleteModel.delete() never calls super().delete()), so historical projects keep resolving their client with no extra code.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="clients.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this project belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "db_table": "project",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"], name="project_company_status_idx"
                    )
                ],
            },
        ),
    ]
