# Generated by Django 5.2.17 on 2026-08-31 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Single responsible user (Database_Schema.md's `assigned_to` column) — not the multi-user \"team\" concept implied by 04_API/Project_API.md's /team endpoints, which is the separate ProjectMember table below (BE-026), a documented deviation from Migration_Plan.md. assigned_to must belong to the same Company as this Project — enforced by validators.validate_assignee_company_membership (BE-025).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who added this member to the project, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Tenant company this membership belongs to (denormalized from project.company).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="company.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this membership is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The member user. SET_NULL (not CASCADE) so a hard-deleted user's historical membership record is preserved, mirroring Project.assigned_to's own SET_NULL choice.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "project member",
                "verbose_name_plural": "project members",
                "db_table": "project_member",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("project", "user"),
                        name="unique_active_project_member",
                    )
                ],
            },
        ),
    ]
