# Generated by Django 5.2.17 on 2026-08-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status_before_hold",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("planning", "Planning"),
                    ("design", "Design"),
                    ("quotation", "Quotation"),
                    ("approved", "Approved"),
                    ("execution", "Execution"),
                    ("quality_check", "Quality Check"),
                    ("handover", "Handover"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="",
                help_text="Internal bookkeeping only (not part of the documented API surface) — the status this project was in immediately before it was last moved to ON_HOLD. ProjectService.transition_status (BE-027) sets this on entering ON_HOLD and clears it on leaving ON_HOLD; it is the only valid resume target per get_allowed_next_statuses above (Backend Lead decision, 2026-08-31: On Hold resumes only to its exact prior status, not to an arbitrary caller-chosen one).",
                max_length=20,
            ),
        ),
    ]
