"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
Configured for BE-002 and BE-003 (Install Core Dependencies) — see BACKEND_TASKS.md.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Environment Variable Handling (django-environ) -------------------------
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=(str, "django-insecure-fv5f2u((b)d0rj8z#hrnikk2vcg!w6c%mc7521c^s_4thv1gxg"),
    DJANGO_ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
    DJANGO_LOG_LEVEL=(str, "INFO"),
    DJANGO_SECURE_SSL_REDIRECT=(bool, False),
    DJANGO_SECURE_HSTS_SECONDS=(int, 31536000),
    DB_NAME=(str, "int_projects_dev"),
    DB_USER=(str, "postgres"),
    DB_PASSWORD=(str, "postgres"),
    DB_HOST=(str, "localhost"),
    DB_PORT=(str, "5432"),
    CORS_ALLOWED_ORIGINS=(list, ["http://localhost:5173", "http://127.0.0.1:5173"]),
    DJANGO_CSRF_TRUSTED_ORIGINS=(list, []),
    CELERY_BROKER_URL=(str, "redis://localhost:6379/0"),
    CELERY_RESULT_BACKEND=(str, "redis://localhost:6379/0"),
    STORAGE_BACKEND=(str, "local"),
    AWS_S3_SIGNED_URL_EXPIRE_SECONDS=(int, 3600),
    EMAIL_HOST=(str, ""),
    EMAIL_PORT=(int, 587),
    EMAIL_HOST_USER=(str, ""),
    EMAIL_HOST_PASSWORD=(str, ""),
    EMAIL_USE_TLS=(bool, True),
)

# Read .env file if present
env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(str(env_file))


# --- Core Settings ----------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback below is the insecure key django-admin generated for local dev
# only (BE-001). Every real environment (staging/production) MUST set
# DJANGO_SECRET_KEY via the platform's secrets manager — see
# 07_DevOps/Production.md §5.
_INSECURE_DEFAULT_SECRET_KEY = "django-insecure-fv5f2u((b)d0rj8z#hrnikk2vcg!w6c%mc7521c^s_4thv1gxg"
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (secure-by-default) — local/dev environments must
# explicitly opt in via DJANGO_DEBUG=true (see backend/.env.example).
DEBUG = env("DJANGO_DEBUG")

# A real environment (DEBUG=False) must never boot with the publicly-known
# insecure default key — that key is checked into this repo and reproduced
# in security audit reports, so silently falling back to it in production
# would be a real, exploitable secret exposure. Development/test keeps
# working unchanged since DEBUG=True there.
if not DEBUG and SECRET_KEY == _INSECURE_DEFAULT_SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set to a real, unique secret when DEBUG=False. "
        "Refusing to start with the insecure development default in a "
        "non-debug environment — see 07_DevOps/Production.md §5."
    )

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS") if not DEBUG else env("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
APPEND_SLASH = False


# --- Application Definition -------------------------------------------------

INSTALLED_APPS = [
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party core dependencies (BE-003)
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    # Internal apps (BE-004+)
    "apps.common",
    "apps.users",
    "apps.authentication",
    "apps.company",
    "apps.audit",
    "apps.clients",
    "apps.leads",
    "apps.projects",
    "apps.site_visits",
    "apps.products",
    "apps.boq",
    "apps.quotations",
    "apps.invoices",
    "apps.payments",
    "apps.expenses",
    "apps.reports",
    "apps.documents",
    "apps.dashboard",
]

AUTH_USER_MODEL = "users.User"


MIDDLEWARE = [
    "apps.common.middleware.RequestIDMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # Serves STATIC_ROOT directly from Gunicorn in production (compressed +
    # far-future cache headers via ManifestStaticFilesStorage below) -- no
    # separate nginx container/volume needed to reach these files, since the
    # host-level nginx reverse-proxying to Gunicorn (see the deployment
    # guide) never needs to know where they live on disk. A no-op locally:
    # DEBUG=true serves static files through Django's own dev static
    # handler instead, same as always.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# --- Database ---------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# --- Password Validation ----------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# --- Internationalization ---------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# --- Static and Media Files -------------------------------------------------
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Object Storage (BE-078) --------------------------------------------
#
# `apps.common.storage` is the only place business apps touch a storage
# backend directly -- everything below exists purely so that module's
# `storages["default"]`/`storages["private"]` lookups resolve to the right
# concrete backend, selected entirely by `STORAGE_BACKEND` (never inferred
# from DEBUG -- an explicit choice, so a real deployment can't silently
# fall back to local disk just because someone forgot to set it, and local
# dev never needs AWS credentials just to run `manage.py runserver`).
#
# "default" (PUBLIC scope: product images, company logos) -- publicly
# readable, permanent URLs, unchanged from how Product.imageUrl has always
# worked. "private" (PRIVATE scope: project documents, expense/payment
# receipts) -- never publicly reachable; local dev points it at a plain
# filesystem directory *outside* MEDIA_ROOT with no base_url configured at
# all (so `.url()` against it deliberately raises -- access only ever goes
# through `apps.common.storage.open_private_file`, streamed by an
# authenticated, tenant/RBAC-checked proxy view, never nginx's public
# `/media/` alias). Production S3 mode gives "private" its own bucket
# path with a private ACL and signed, time-limited URLs regenerated on
# every access, never persisted to the database.
STORAGE_BACKEND = env("STORAGE_BACKEND")

# Whitenoise's manifest storage requires collectstatic to have already run
# (true in the production Docker image, false for a bare `manage.py
# runserver` in local dev) -- gated on DEBUG, not STORAGE_BACKEND, since the
# two are independent choices (a deployment could use STORAGE_BACKEND=local
# for media while still being a real, non-debug production environment).
_staticfiles_backend = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

if STORAGE_BACKEND == "s3":
    from django.core.exceptions import ImproperlyConfigured as _ImproperlyConfigured

    _S3_REQUIRED_ENV = [
        "AWS_STORAGE_BUCKET_NAME",
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
        "AWS_S3_REGION_NAME",
    ]
    _s3_missing = [name for name in _S3_REQUIRED_ENV if not env(name, default="")]
    if _s3_missing:
        # Fail loudly at boot, not silently fall back to local disk -- a
        # deployment that explicitly selected S3 and is missing its
        # required config is a real misconfiguration, not something to
        # paper over (§22's "fail safely... do not silently fall back").
        raise _ImproperlyConfigured(
            "STORAGE_BACKEND=s3 requires the following environment "
            f"variable(s), which are missing or empty: {', '.join(_s3_missing)}. "
            "See backend/.env.example for the full S3 configuration block."
        )

    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME")
    # Both optional: a non-AWS S3-compatible provider (MinIO, DigitalOcean
    # Spaces, Cloudflare R2, ...) sets AWS_S3_ENDPOINT_URL; a CDN in front
    # of the public bucket sets AWS_S3_CUSTOM_DOMAIN for the "default"
    # (public) storage only -- "private" never uses a CDN domain, since
    # its whole point is that a URL is never durably public.
    _s3_endpoint_url = env("AWS_S3_ENDPOINT_URL", default="") or None
    _s3_custom_domain = env("AWS_S3_CUSTOM_DOMAIN", default="") or None

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "endpoint_url": _s3_endpoint_url,
                "custom_domain": _s3_custom_domain,
                "default_acl": "public-read",
                "querystring_auth": False,
                "location": "public",
            },
        },
        "private": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "endpoint_url": _s3_endpoint_url,
                "default_acl": "private",
                "querystring_auth": True,
                "querystring_expire": env("AWS_S3_SIGNED_URL_EXPIRE_SECONDS"),
                "location": "private",
            },
        },
        "staticfiles": {"BACKEND": _staticfiles_backend},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "private": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                # Deliberately outside MEDIA_ROOT and with no base_url --
                # nginx's `/media/` alias (backend/nginx/nginx.conf) can
                # never serve this directory even by accident, and calling
                # `.url()` against it raises rather than silently
                # returning a URL nothing actually serves.
                "location": str(BASE_DIR / "media_private"),
                "base_url": None,
            },
        },
        "staticfiles": {"BACKEND": _staticfiles_backend},
    }


# --- Django REST Framework (DRF) --------------------------------------------
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.authentication.authentication.TenantJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "apps.common.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 25,
    "EXCEPTION_HANDLER": "apps.common.exceptions.custom_exception_handler",
    # ScopedRateThrottle only throttles a view that declares throttle_scope
    # (rest_framework.throttling.ScopedRateThrottle.allow_request() returns
    # True immediately otherwise) — safe as a global default, since it
    # leaves every view without a scope completely unthrottled.
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "auth_login": "10/min",
        "platform_auth_login": "10/min",
        "auth_forgot_password": "5/min",
        "auth_reset_password": "10/min",
        "auth_refresh": "30/min",
    },
    # BrowsableAPIRenderer is a real, if low-severity, information-exposure
    # surface in production (renders an interactive HTML API browser to any
    # requester) — restrict to JSON there. DEBUG=True keeps the browsable
    # renderer for local development, so DX is unaffected.
    "DEFAULT_RENDERER_CLASSES": (
        ["rest_framework.renderers.JSONRenderer", "rest_framework.renderers.BrowsableAPIRenderer"]
        if DEBUG
        else ["rest_framework.renderers.JSONRenderer"]
    ),
}


# --- SimpleJWT --------------------------------------------------------------
# https://django-rest-framework-simplejwt.readthedocs.io/

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "sub",
    "AUTH_TOKEN_CLASSES": (
        "apps.authentication.tokens.CompanyUserAccessToken",
        "apps.authentication.tokens.PlatformAdminAccessToken",
        "rest_framework_simplejwt.tokens.AccessToken",
    ),
}


# --- OpenAPI / Swagger (drf-spectacular) ------------------------------------
# https://drf-spectacular.readthedocs.io/

SPECTACULAR_SETTINGS = {
    "TITLE": "INT Projects SaaS API",
    "DESCRIPTION": "Multi-Tenant Architecture & Interior Management SaaS API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # BE-025: Company.status and Project.status are both TextChoices named
    # "status" — drf-spectacular can't tell them apart by field name alone
    # and falls back to an unstable hash-suffixed component name
    # ("Status4e9Enum"). Naming them explicitly keeps the schema stable.
    "ENUM_NAME_OVERRIDES": {
        "CompanyStatusEnum": "apps.company.models.CompanyStatus",
        "ProjectStatusEnum": "apps.projects.models.ProjectStatus",
        "ProductStatusEnum": "apps.products.models.ProductStatus",
        "LeadStatusEnum": "apps.leads.models.LeadStatus",
        "QuotationStatusEnum": "apps.quotations.models.QuotationStatus",
        "InvoiceStatusEnum": "apps.invoices.models.InvoiceStatus",
        "CompanyMembershipStatusEnum": "apps.users.models.CompanyMembershipStatus",
    },
}


# --- CORS (django-cors-headers) ---------------------------------------------
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS") if not DEBUG else env(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:5173", "http://127.0.0.1:5173"]
)
CORS_ALLOW_CREDENTIALS = True

# Vite falls back to the next free port (5174, 5175, ...) whenever 5173 is
# already in use, which silently breaks the fixed-origin allowlist above in
# local dev. Only in DEBUG (never true in production, per this project's own
# settings-hardening tests) also allow any localhost/127.0.0.1 port so a dev
# server on a different port isn't blocked by CORS.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ]


# --- CSRF ---------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#csrf-trusted-origins
#
# This API is JWT-bearer-token authenticated end to end (no
# SessionAuthentication in REST_FRAMEWORK), so CSRF only actually matters
# for django.contrib.admin's own session+cookie login. Empty by default —
# Django simply trusts nothing extra beyond same-origin requests, which is
# already maximally safe and doesn't affect local dev (admin is normally
# accessed same-origin there). A real deployment behind HTTPS, especially
# one where the frontend/admin are reached through a different origin than
# Django sees itself as (a reverse proxy, a split app/api subdomain), sets
# DJANGO_CSRF_TRUSTED_ORIGINS explicitly — comma-separated full origins
# including scheme, e.g. "https://app.example.com,https://api.example.com".
# Never a wildcard; never inferred from CORS_ALLOWED_ORIGINS, since CORS
# (cross-origin fetch/XHR to the JSON API) and CSRF (trusted origins for
# admin's session cookie) are different concerns with different risk
# profiles — conflating them would trust the SPA's own origin for
# cookie-based admin form submission it was never meant to have.
CSRF_TRUSTED_ORIGINS = env("DJANGO_CSRF_TRUSTED_ORIGINS")


# --- Celery & Redis ---------------------------------------------------------
# https://docs.celeryq.dev/

CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE


# --- Email & Password Reset ------------------------------------------------
# Defaults to the console backend (dev-only, prints to stdout) unless
# DJANGO_EMAIL_BACKEND is set -- a real deployment sets it to
# "django.core.mail.backends.smtp.EmailBackend" and fills in the EMAIL_*
# variables below (any SMTP provider works: Hostinger's own mailbox,
# SendGrid, Mailgun, Brevo, ...). Without this, password-reset and
# account-activation emails silently vanish into a container's stdout that
# nobody reads in production -- BE-080's "Set Owner Password" workaround
# exists specifically because this wasn't configured for this session's
# own dev environment either.
EMAIL_BACKEND = env("DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@intprojects.com")
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")
PASSWORD_RESET_TOKEN_LIFETIME = timedelta(hours=1)


# --- Logging ----------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/logging/

DJANGO_LOG_LEVEL = env("DJANGO_LOG_LEVEL")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
}


# --- Security Hardening -----------------------------------------------------

if not DEBUG:
    SECURE_SSL_REDIRECT = env("DJANGO_SECURE_SSL_REDIRECT")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = env("DJANGO_SECURE_HSTS_SECONDS")
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

