"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
Configured for BE-002 and BE-003 (Install Core Dependencies) — see BACKEND_TASKS.md.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Environment Variable Handling (django-environ) -------------------------
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=(str, "django-insecure-fv5f2u((b)d0rj8z#hrnikk2vcg!w6c%mc7521c^s_4thv1gxg"),
    DJANGO_ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
    DJANGO_LOG_LEVEL=(str, "INFO"),
    DJANGO_SECURE_SSL_REDIRECT=(bool, False),
    DJANGO_SECURE_HSTS_SECONDS=(int, 31536000),
    DB_NAME=(str, "int_projects_dev"),
    DB_USER=(str, "postgres"),
    DB_PASSWORD=(str, "postgres"),
    DB_HOST=(str, "localhost"),
    DB_PORT=(str, "5432"),
    CORS_ALLOWED_ORIGINS=(list, ["http://localhost:5173", "http://127.0.0.1:5173"]),
    CELERY_BROKER_URL=(str, "redis://localhost:6379/0"),
    CELERY_RESULT_BACKEND=(str, "redis://localhost:6379/0"),
)

# Read .env file if present
env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(str(env_file))


# --- Core Settings ----------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback below is the insecure key django-admin generated for local dev
# only (BE-001). Every real environment (staging/production) MUST set
# DJANGO_SECRET_KEY via the platform's secrets manager — see
# 07_DevOps/Production.md §5.
_INSECURE_DEFAULT_SECRET_KEY = "django-insecure-fv5f2u((b)d0rj8z#hrnikk2vcg!w6c%mc7521c^s_4thv1gxg"
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (secure-by-default) — local/dev environments must
# explicitly opt in via DJANGO_DEBUG=true (see backend/.env.example).
DEBUG = env("DJANGO_DEBUG")

# A real environment (DEBUG=False) must never boot with the publicly-known
# insecure default key — that key is checked into this repo and reproduced
# in security audit reports, so silently falling back to it in production
# would be a real, exploitable secret exposure. Development/test keeps
# working unchanged since DEBUG=True there.
if not DEBUG and SECRET_KEY == _INSECURE_DEFAULT_SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set to a real, unique secret when DEBUG=False. "
        "Refusing to start with the insecure development default in a "
        "non-debug environment — see 07_DevOps/Production.md §5."
    )

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS") if not DEBUG else env("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
APPEND_SLASH = False


# --- Application Definition -------------------------------------------------

INSTALLED_APPS = [
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party core dependencies (BE-003)
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    # Internal apps (BE-004+)
    "apps.common",
    "apps.users",
    "apps.authentication",
    "apps.company",
    "apps.audit",
    "apps.clients",
    "apps.projects",
    "apps.products",
]

AUTH_USER_MODEL = "users.User"


MIDDLEWARE = [
    "apps.common.middleware.RequestIDMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# --- Database ---------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# --- Password Validation ----------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# --- Internationalization ---------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# --- Static and Media Files -------------------------------------------------
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Django REST Framework (DRF) --------------------------------------------
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.authentication.authentication.TenantJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "apps.common.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 25,
    "EXCEPTION_HANDLER": "apps.common.exceptions.custom_exception_handler",
    # ScopedRateThrottle only throttles a view that declares throttle_scope
    # (rest_framework.throttling.ScopedRateThrottle.allow_request() returns
    # True immediately otherwise) — safe as a global default, since it
    # leaves every view without a scope completely unthrottled.
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "auth_login": "10/min",
        "platform_auth_login": "10/min",
        "auth_forgot_password": "5/min",
        "auth_reset_password": "10/min",
        "auth_refresh": "30/min",
    },
    # BrowsableAPIRenderer is a real, if low-severity, information-exposure
    # surface in production (renders an interactive HTML API browser to any
    # requester) — restrict to JSON there. DEBUG=True keeps the browsable
    # renderer for local development, so DX is unaffected.
    "DEFAULT_RENDERER_CLASSES": (
        ["rest_framework.renderers.JSONRenderer", "rest_framework.renderers.BrowsableAPIRenderer"]
        if DEBUG
        else ["rest_framework.renderers.JSONRenderer"]
    ),
}


# --- SimpleJWT --------------------------------------------------------------
# https://django-rest-framework-simplejwt.readthedocs.io/

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "sub",
    "AUTH_TOKEN_CLASSES": (
        "apps.authentication.tokens.CompanyUserAccessToken",
        "apps.authentication.tokens.PlatformAdminAccessToken",
        "rest_framework_simplejwt.tokens.AccessToken",
    ),
}


# --- OpenAPI / Swagger (drf-spectacular) ------------------------------------
# https://drf-spectacular.readthedocs.io/

SPECTACULAR_SETTINGS = {
    "TITLE": "INT Projects SaaS API",
    "DESCRIPTION": "Multi-Tenant Architecture & Interior Management SaaS API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # BE-025: Company.status and Project.status are both TextChoices named
    # "status" — drf-spectacular can't tell them apart by field name alone
    # and falls back to an unstable hash-suffixed component name
    # ("Status4e9Enum"). Naming them explicitly keeps the schema stable.
    "ENUM_NAME_OVERRIDES": {
        "CompanyStatusEnum": "apps.company.models.CompanyStatus",
        "ProjectStatusEnum": "apps.projects.models.ProjectStatus",
    },
}


# --- CORS (django-cors-headers) ---------------------------------------------
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS") if not DEBUG else env(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:5173", "http://127.0.0.1:5173"]
)
CORS_ALLOW_CREDENTIALS = True


# --- Celery & Redis ---------------------------------------------------------
# https://docs.celeryq.dev/

CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE


# --- Email & Password Reset ------------------------------------------------
EMAIL_BACKEND = env("DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@intprojects.com")
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")
PASSWORD_RESET_TOKEN_LIFETIME = timedelta(hours=1)


# --- Logging ----------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/logging/

DJANGO_LOG_LEVEL = env("DJANGO_LOG_LEVEL")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
}


# --- Security Hardening -----------------------------------------------------

if not DEBUG:
    SECURE_SSL_REDIRECT = env("DJANGO_SECURE_SSL_REDIRECT")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = env("DJANGO_SECURE_HSTS_SECONDS")
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

