# Generated by Django 5.2.17 on 2026-08-31 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("projects", "0003_project_status_before_hold"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text BOQ status. No documented value domain exists.",
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this BOQ belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boqs",
                        to="company.company",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="The project this BOQ belongs to. One BOQ per project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOQ",
                "verbose_name_plural": "BOQs",
                "db_table": "boq",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BOQSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Section name.", max_length=255)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order among this BOQ's sections (auto-assigned).",
                    ),
                ),
                (
                    "boq",
                    models.ForeignKey(
                        help_text="The BOQ this section belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="boq.boq",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOQ section",
                "verbose_name_plural": "BOQ sections",
                "db_table": "boq_section",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
