# Generated by Django 5.2.17 on 2026-08-31 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0001_initial"),
        ("products", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOQItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Item description. Defaults from the product's name if a product is referenced.",
                        max_length=500,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of this item.",
                        max_digits=12,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nos", "Nos"),
                            ("sqft", "Sq.ft"),
                            ("sqm", "Sq.m"),
                            ("running_ft", "Running ft"),
                            ("kg", "Kg"),
                            ("litre", "Litre"),
                            ("set", "Set"),
                            ("job", "Job"),
                        ],
                        default="",
                        help_text="Unit of measure — reuses apps.products.models.ProductUnit's 8 documented values (FRS.md §11/§12 name the same unit list for both Product and BOQ items). Defaults from the referenced product's unit if not supplied.",
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate per unit. Defaults from the product's default selling rate if a product is referenced.",
                        max_digits=14,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage applied to this item.",
                        max_digits=5,
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax percentage applied to this item. Defaults from the product's tax rate if referenced.",
                        max_digits=5,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Server-computed: quantity * rate. Never client-writable.",
                        max_digits=14,
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False,
                        help_text="Excluded from the BOQ's default summary total when true.",
                    ),
                ),
                (
                    "is_alternative",
                    models.BooleanField(
                        default=False,
                        help_text="Excluded from the BOQ's default summary total when true.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form notes about this item.",
                    ),
                ),
                (
                    "boq_section",
                    models.ForeignKey(
                        help_text="The section this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="boq.boqsection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional catalog product reference. Null for a free-text item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOQ item",
                "verbose_name_plural": "BOQ items",
                "db_table": "boq_item",
                "ordering": ["created_at"],
            },
        ),
    ]
