# Generated by Django 5.2.17 on 2026-09-07 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="`<module>.<action>` permission code, e.g. 'invoice.view'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("export", "Export"),
                            ("manage", "Manage"),
                            ("financial_access", "Financial Access"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
                "db_table": "permission",
                "ordering": ["module", "action"],
            },
        ),
        migrations.AddField(
            model_name="companymembership",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role assigned to this membership within the company. Null until an admin assigns one (BE-050) — a membership with no role has no permission codes and, per RBAC's fail-closed default, no access beyond bare tenant membership until BE-054 enforcement lands. Must belong to the same company as this membership (validated in apps.users.validators, not by a DB constraint, since Django has no native cross-field FK-company-match constraint).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="users.role",
            ),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="users.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "role permission",
                "verbose_name_plural": "role permissions",
                "db_table": "role_permission",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("role", "permission"),
                        name="unique_active_role_permission",
                    )
                ],
            },
        ),
    ]
