# Generated by Django 5.2.17 on 2026-09-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_logo_storage_key_company_logo_url'),
        ('users', '0008_grant_report_view_to_operational_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='system_key',
            field=models.CharField(blank=True, default=None, editable=False, help_text="Stable machine identity for a default/system role (BE-069), e.g. 'owner'. NULL for every customer-created role, including one a customer names 'Owner' -- a role's system identity is never inferred from its display `name`, which remains freely editable. Set only by RoleService.seed_default_roles_for_company at company-creation time (or by the historical backfill migration); never accepted from any API input. See apps.users.permission_catalog.OWNER_SYSTEM_KEY for the one value with dedicated protection semantics.", max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__isnull', False)), fields=('company', 'system_key'), name='unique_system_key_per_company'),
        ),
    ]
