# Generated by Django 5.2.17 on 2026-09-01 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("projects", "0003_project_status_before_hold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("vendor", models.CharField(blank=True, default="", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "receipt_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who recorded this expense.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this expense belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="company.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee this expense relates to, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incurred_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this expense is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "expense",
                "verbose_name_plural": "expenses",
                "db_table": "expense",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "project"], name="expense_comp_project_idx"
                    ),
                    models.Index(
                        fields=["company", "approval_status"],
                        name="expense_comp_status_idx",
                    ),
                ],
            },
        ),
    ]
