# Generated by Django 5.2.17 on 2026-09-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt_storage_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal-only (never publicly exposed). The private object-storage key backing the receipt, set only when it was uploaded via POST /expenses/receipts/upload (BE-078). Blank for a legacy/manual receipt_url registration.",
                max_length=500,
            ),
        ),
    ]
