# Generated by Django 5.2.17 on 2026-08-25 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Module-level entity name, e.g. 'role', 'company'.",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Primary key of the affected record. Not a FK — spans many entity tables.",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True,
                        help_text="Allowlisted field snapshot before the change. Null for create.",
                        null=True,
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True,
                        help_text="Allowlisted field snapshot after the change. Null for delete.",
                        null=True,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        help_text="Correlates to the same requestId in operational logs and API responses.",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action. Null for system/automated actions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="The tenant this entry concerns. Null for platform-level actions with no company context — the one deliberate exception to the usual NOT NULL tenant-scope rule (Database_Schema.md). Also set null (not cascade-deleted) if the company is ever hard-deleted — the audit row itself must outlive the tenant record, per the 'never-expired' requirement this model exists to satisfy.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log entry",
                "verbose_name_plural": "audit log entries",
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_log_entity__c2633a_idx",
                    ),
                    models.Index(
                        fields=["company", "created_at"],
                        name="audit_log_company_5ae5ba_idx",
                    ),
                ],
            },
        ),
    ]
