# Generated by Django 5.2.17 on 2026-08-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("approve", "Approve"),
                    ("login_success", "Login Success"),
                    ("login_failure", "Login Failure"),
                    ("logout", "Logout"),
                    ("token_refresh", "Token Refresh"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_completed", "Password Reset Completed"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
