# Generated by Django 5.2.17 on 2026-08-24 12:32

import apps.company.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company trading or legal name.", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="trial",
                        help_text="Subscription lifecycle status.",
                        max_length=50,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR",
                        help_text="Default currency code (e.g. INR, USD).",
                        max_length=10,
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True,
                        help_text="Goods and Services Tax Identification Number (GSTIN).",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=apps.company.models.get_default_company_settings,
                        help_text="Tenant-specific configuration and preferences.",
                    ),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "db_table": "company",
                "ordering": ["-created_at"],
            },
        ),
    ]
