# Generated by Django 5.2.17 on 2026-09-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo_storage_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal-only (never serialized). The object-storage key backing logo_url, set only when the logo was uploaded via POST /company/{id}/logo/upload. Mirrors Product.image_storage_key's reasoning exactly.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of the company's branding logo, if any (BE-078).",
                max_length=500,
            ),
        ),
    ]
