# Generated by Django 5.2.17 on 2026-08-27 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Client's primary contact/individual name.",
                        max_length=255,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="The client's own business/trading name, if applicable.",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Client's primary contact email address.",
                        max_length=254,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="Client's primary contact mobile number.",
                        max_length=20,
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        help_text="Client's GST Identification Number (GSTIN), if applicable.",
                        max_length=15,
                    ),
                ),
                (
                    "addresses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of address records for this client (shape not yet standardized).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form internal notes about this client.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this client belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "db_table": "client",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "name"], name="client_company_name_idx"
                    )
                ],
            },
        ),
    ]
