# Generated by Django 5.2.17 on 2026-09-15 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("company", "0002_company_logo_storage_key_company_logo_url"),
        ("projects", "0003_project_status_before_hold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Prospect's primary contact/individual name.",
                        max_length=255,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The prospect's own business/trading name, if applicable.",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Prospect's primary contact email address.",
                        max_length=254,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Prospect's primary contact mobile number.",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text lead source (e.g. referral, website, walk-in). No fixed vocabulary is documented.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("qualified", "Qualified"),
                            ("follow_up", "Follow-up"),
                            ("site_visit_scheduled", "Site Visit Scheduled"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Lead lifecycle status.",
                        max_length=30,
                    ),
                ),
                (
                    "loss_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Required when status is LOST (enforced in LeadService.mark_lost, not a DB constraint).",
                    ),
                ),
                (
                    "follow_up_reminder_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Optional future follow-up date/time, settable independent of status (FRS §8: 'optional future follow-up date').",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form internal notes about this lead.",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Sales/CRM user currently working this lead, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this lead belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="company.company",
                    ),
                ),
                (
                    "converted_client",
                    models.ForeignKey(
                        blank=True,
                        help_text="The real Client created when this lead was converted (LeadService.convert_lead). Set once, never cleared.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_from_leads",
                        to="clients.client",
                    ),
                ),
                (
                    "converted_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Project optionally created at the same time as conversion, if requested.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_from_leads",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "db_table": "lead",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"], name="lead_company_status_idx"
                    ),
                    models.Index(
                        fields=["company", "assigned_to"],
                        name="lead_company_assignee_idx",
                    ),
                ],
            },
        ),
    ]
