# Generated by Django 5.2.17 on 2026-09-01 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("projects", "0003_project_status_before_hold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="The kind of entity this document is attached to, e.g. 'project', 'quotation', 'invoice', 'expense'.",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        help_text="The specific entity's primary key. Not a real FK -- spans many entity tables."
                    ),
                ),
                ("file_url", models.URLField(max_length=500)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Auto-assigned: next version among documents sharing this (entity_type, entity_id).",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this document belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="company.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this document belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who uploaded this document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "db_table": "document",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["project"], name="document_project_idx"),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="document_entity_idx"
                    ),
                ],
            },
        ),
    ]
