# Generated by Django 5.2.17 on 2026-09-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_storage_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal-only (never publicly exposed). The private object-storage key backing this document, set only when it was uploaded via POST /documents/upload (BE-078). Blank for a legacy/manual file_url registration.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
