# Generated by Django 5.2.17 on 2026-09-01 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boq", "0002_boqitem"),
        ("clients", "0001_initial"),
        ("company", "0001_initial"),
        ("products", "0003_product"),
        ("projects", "0003_project_status_before_hold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        db_index=True,
                        help_text="Per-company sequential quote number (e.g. QT-000001), shared across every version of the same quotation.",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version number within this quote_number's revision chain. Starts at 1.",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("terms", models.TextField(blank=True, default="")),
                (
                    "payment_schedule",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Free-form payment schedule structure (e.g. milestone/percentage/amount entries).",
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("internal_review", "Internal Review"),
                            ("sent", "Sent"),
                            ("revision_requested", "Revision Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "boq",
                    models.ForeignKey(
                        blank=True,
                        help_text="The BOQ this quotation was generated from, if any. Null for a manually-built quotation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to="boq.boq",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this quotation is for. Always derived from the project's own client, never caller-supplied.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="clients.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this quotation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="company.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this quotation is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "quotation",
                "verbose_name_plural": "quotations",
                "db_table": "quotation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nos", "Nos"),
                            ("sqft", "Sq.ft"),
                            ("sqm", "Sq.m"),
                            ("running_ft", "Running ft"),
                            ("kg", "Kg"),
                            ("litre", "Litre"),
                            ("set", "Set"),
                            ("job", "Job"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Server-computed: quantity * rate. Never client-writable.",
                        max_digits=14,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional catalog product reference. Null for a free-text item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_items",
                        to="products.product",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        help_text="The quotation this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "quotation item",
                "verbose_name_plural": "quotation items",
                "db_table": "quotation_item",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["project"], name="quotation_project_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["company", "quote_number"], name="quotation_comp_qnum_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("company", "quote_number", "version"),
                name="quotation_comp_qnum_version_uniq",
            ),
        ),
    ]
