# Generated by Django 5.2.17 on 2026-09-01 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("company", "0001_initial"),
        ("projects", "0003_project_status_before_hold"),
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("invoice_number", models.CharField(db_index=True, max_length=50)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_terms", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Persisted base status. Never 'overdue' -- see InvoiceStatus docstring.",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this invoice is for. Always derived from the project's own client, never caller-supplied.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="clients.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this invoice belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="company.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this invoice is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="projects.project",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved quotation this invoice was generated from, if any. Null for an ad hoc invoice.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
                "db_table": "invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nos", "Nos"),
                            ("sqft", "Sq.ft"),
                            ("sqm", "Sq.m"),
                            ("running_ft", "Running ft"),
                            ("kg", "Kg"),
                            ("litre", "Litre"),
                            ("set", "Set"),
                            ("job", "Job"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Server-computed: quantity * rate. Never client-writable.",
                        max_digits=14,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="The invoice this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice item",
                "verbose_name_plural": "invoice items",
                "db_table": "invoice_item",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["project"], name="invoice_project_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "invoice_number"], name="invoice_comp_number_idx"
            ),
        ),
    ]
