# Generated by Django 5.2.17 on 2026-09-01 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("company", "0001_initial"),
        ("invoices", "0001_initial"),
        ("projects", "0003_project_status_before_hold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("method", models.CharField(blank=True, default="", max_length=50)),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "receipt_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this payment is from. Always derived from the invoice's own client.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="clients.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this payment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="company.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="The invoice this payment is recorded against.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this payment relates to. Always derived from the invoice's own project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "db_table": "payment",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["invoice"], name="payment_invoice_idx"),
                    models.Index(
                        fields=["company", "project"], name="payment_comp_project_idx"
                    ),
                ],
            },
        ),
    ]
