# Generated by Django 5.2.17 on 2026-08-31 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Category name.", max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this category belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_categories",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
                "db_table": "product_category",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "name"], name="product_cat_comp_name_idx"
                    )
                ],
            },
        ),
    ]
