# Generated by Django 5.2.17 on 2026-08-31 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSubcategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Subcategory name.", max_length=255),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The parent category this subcategory belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.productcategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this subcategory belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_subcategories",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "product subcategory",
                "verbose_name_plural": "product subcategories",
                "db_table": "product_subcategory",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "category"], name="prod_subcat_comp_cat_idx"
                    )
                ],
            },
        ),
    ]
