# Generated by Django 5.2.17 on 2026-08-31 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("products", "0002_productsubcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product/work item name.", max_length=255
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL of the product's image, if any.",
                        max_length=500,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nos", "Nos"),
                            ("sqft", "Sq.ft"),
                            ("sqm", "Sq.m"),
                            ("running_ft", "Running ft"),
                            ("kg", "Kg"),
                            ("litre", "Litre"),
                            ("set", "Set"),
                            ("job", "Job"),
                        ],
                        default="",
                        help_text="Unit of measure. One of the 8 documented values.",
                        max_length=20,
                    ),
                ),
                (
                    "default_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default cost price for this product.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "default_selling_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default selling rate for this product.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tax rate percentage applied to this product by default.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        help_text="Product catalog status.",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company this product belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="company.company",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        help_text="The subcategory this product belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.productsubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "product",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"], name="product_company_status_idx"
                    ),
                    models.Index(
                        fields=["subcategory"], name="product_subcategory_idx"
                    ),
                ],
            },
        ),
    ]
