# Generated by Django 5.2.17 on 2026-09-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_storage_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal-only (never serialized). The object-storage key backing image_url, set only when the image was uploaded via POST /products/images/upload (BE-078). Blank when image_url was entered manually via the alternate URL-entry flow -- in that case this app does not own the file and must never attempt to delete it. Used by ProductService.update_product to safely clean up a superseded image on replace/remove without ever deleting a file this app doesn't own.",
                max_length=500,
            ),
        ),
    ]
